name: Pipeline

on:
  pull_request:
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  testing:
    uses: ./.github/workflows/test.yml   

  building:
    needs: testing
    if: ${{ success() }}
    uses: ./.github/workflows/build.yml  